language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-vertex' ]; then cd .. && eval "mv $currentfolder generator-vertex" && cd generator-vertex; fi

